# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\",\n\x05urmom\x12\x17\n\x0fnumberOfServers\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\"\x06\n\x04Null2/\n\nRouteGuide\x12!\n\x0eGetInformation\x12\x06.urmom\x1a\x05.Null\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_URMOM']._serialized_start=17
  _globals['_URMOM']._serialized_end=61
  _globals['_NULL']._serialized_start=63
  _globals['_NULL']._serialized_end=69
  _globals['_ROUTEGUIDE']._serialized_start=71
  _globals['_ROUTEGUIDE']._serialized_end=118
# @@protoc_insertion_point(module_scope)
